import { CoffeeData } from '../../reducers/reducer'

export const Coffees: CoffeeData[] = [
  {
    id: '1',
    imagem: { coffeeImage: 'tradicional' },
    tags: ['TRADICIONAL'],
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '2',
    imagem: { coffeeImage: 'americano' },
    tags: ['TRADICIONAL'],
    nome: 'Expresso Americano',
    descricao: 'Expresso diluído, menos intenso que o tradicional',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '3',
    imagem: { coffeeImage: 'latte' },
    tags: ['TRADICIONAL', 'COM LEITE'],
    nome: 'Latte',
    descricao:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '4',
    imagem: { coffeeImage: 'gelado' },
    tags: ['TRADICIONAL', 'GELADO'],
    nome: 'Expresso Gelado',
    descricao: 'Bebida preparada com café expresso e cubos de gelo',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '5',
    imagem: { coffeeImage: 'leite' },
    tags: ['TRADICIONAL', 'COM LEITE'],
    nome: 'Café com Leite',
    descricao: 'Meio a meio de expresso tradicional com leite vaporizado',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '6',
    imagem: { coffeeImage: 'expresso' },
    tags: ['TRADICIONAL'],
    nome: 'Expresso Cremoso',
    descricao: 'Café expresso tradicional com espuma cremosa',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '7',
    imagem: { coffeeImage: 'capuccino' },
    tags: ['TRADICIONAL', 'COM LEITE'],
    nome: 'Capuccino',
    descricao:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '8',
    imagem: { coffeeImage: 'macchiato' },
    tags: ['TRADICIONAL', 'COM LEITE'],
    nome: 'Macchiato',
    descricao: 'Café expresso misturado com um pouco de leite quente e espuma',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '9',
    imagem: { coffeeImage: 'mocaccino' },
    tags: ['TRADICIONAL', 'COM LEITE'],
    nome: 'Mocaccino',
    descricao: 'Café expresso com calda de chocolate, pouco leite e espuma',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '10',
    imagem: { coffeeImage: 'chocolate' },
    tags: ['ESPECIAL', 'COM LEITE'],
    nome: 'Chocolate Quente',
    descricao: 'Bebida feita com chocolate dissolvido no leite quente e café',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '11',
    imagem: { coffeeImage: 'cubano' },
    tags: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    nome: 'Cubano',
    descricao:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '12',
    imagem: { coffeeImage: 'havaiano' },
    tags: ['ESPECIAL'],
    nome: 'Havaiano',
    descricao: 'Bebida adocicada preparada com café e leite de coco',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '13',
    imagem: { coffeeImage: 'arabe' },
    tags: ['ESPECIAL'],
    nome: 'Árabe',
    descricao: 'Bebida preparada com grãos de café árabe e especiarias',
    preco: 9.9,
    quantidade: 1,
  },
  {
    id: '14',
    imagem: { coffeeImage: 'irlandes' },
    tags: ['ESPECIAL', 'ALCOÓlICO'],
    nome: 'Irlandês',
    descricao: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    preco: 9.9,
    quantidade: 1,
  },
]
